### ISSUE TITLE
Having an issue with getting started

### ISSUE THREAD

**Issue by m3t4123** [MrFlacko/lancache-script#2]
I'm very new to all this and unsure how I go about making my lancache work, the script worked flawlessly and I've set my DNS on another client to test it out, however anytime I download anything I see no usage on the 'docker stats' section on the server.

Would I have to route my traffic through my router instead or would there be something I have missed

any info would be appreciated

**Comment by MrFlacko** [comment]
What I like using is the program bpytop to show network usage. If you see that there is network traffic in the server when downloading from a host device set up correctly then it is caching the downloads.
